### PR TITLE
Made AwsEbDeploy exit with error if no WAR file found.

### PR DESCRIPTION
**Pull request by alxndrsn**
Hi, just got a bit confused by this plugin when I hadn't run grails-war previously.

Added error and script exit with non-zero status code when WAR file was not found.

### CODE REVIEW

**Comment by kenliu** [comment]
Thanks for your contribution!

**Comment by alxndrsn** [comment]
thanks for your plugin, and fast response :)

**Comment by kenliu** [comment]
NP. BTW if you have any other feedback about the plugin or any desired features please feel free to submit a bug or feature request. I haven't really received any comments from anyone so I don't know how it is working out for people.

**Comment by alxndrsn** [comment]
Yeah feedback can be hard to come by - shame there's not a general comments space on github or the grails plugin portal.

So far just using the plugin for deployments, but it's worked really nicely.  It was a little tricky to get set up with security credentials, so I'll add a bit to the README and send a pull request.

**Comment by alxndrsn** [comment]
Actually credential setup documentation is fine - just my reading skills that need improvement.

**Comment by kenliu** [comment]
I've started working on a proper user manual here: https://github.com/kenliu/grails-elastic-beanstalk/blob/master/src/asciidoc/manual.adoc

It's written in asciidoc instead of gdoc. I'm working on the authentication section but haven't committed it yet.

**Comment by kenliu** [comment]
released this PR in 0.3-SNAPSHOT, would appreciate any help with testing before I release 0.3

**Pull request merged**
