### PR TITLE
Create environment if it does not exist

### PR DESCRIPTION
**Pull request by jvdrean**

### CODE REVIEW

**Comment by kenliu** [comment]
I'm merging this pull request but am going to change the Config.groovy property name from `grails.plugin.awsElasticBeanstalk.templateName` to `grails.plugin.awsElasticBeanstalk.configurationTemplateName` to keep the terminology consistent with Elastic Beanstalk.

**Comment by kenliu** [comment]
BTW this was a really good idea, thanks for your contribution.

**Comment by jvdrean** [comment]
About the appversion + timestamp: the timestamp is indeed unique but I thought it'd make sense to put the appversion in the version field too, WDYT ?

**Comment by kenliu** [comment]
I hadn't thought about it much, but I guess it does make sense. I'm using the plugin in a CI scenario so the version number is not so important because there are so many different (Beanstalk) versions.

However, for a default I think the WAR timestamp is the simplest solution because it's pretty much guaranteed to be complete.

Ultimately I want to implement a way to allow the user to configure their own pattern. I don't the the tool should force the user to use a specific pattern.

**Comment by jvdrean** [comment]
In a CI scenario it makes sense, however do you agree to use the appVersion when it is not a SNAPSHOT ?
In my case I use the plugin for both CI and releases, with the following environmentName (for production) :

environmentName = grails.util.Metadata.current.'app.version'.replaceAll('\.' ,'-')

This allows to use the plugin after building the release and have a new environment created for it, that way the only manual operation remaining is the URL swap

**Comment by kenliu** [comment]
Hey there. I definitely think the plugin should support your use case as described above.

However, as the code currently stands it won't work for my use case since we don't use SNAPSHOT versioning and we just keep the version the same until we move to another release.

I have some changes I'll push tonight to support custom version label formats to support both cases.

**Comment by kenliu** [comment]
I published version 0.2-SNAPSHOT that now allows you to specify a pattern for the version label and description.

You can configure a custom version template that handles the snapshot version as follows:

```
grails.plugin.awsElasticBeanstalk.versionLabelTemplate = '''${applicationVersion.endsWith('SNAPSHOT') ? applicationVersion + '-' + warTimestampDate : applicationVersion}'''
```

**Comment by kenliu** [comment]
correction, that is 0.3-SNAPSHOT

**Comment by jvdrean** [comment]
It's working great, thanks!
FYI, here's what it looks like in my case:

```
environments {
    development {
        grails {
            plugin {
                awsElasticBeanstalk {
                    versionLabelTemplate = '''${warTimestampDate}'''
                }
            }
        }
    }
    production {
        grails {
            plugin {
                awsElasticBeanstalk {
                    versionLabelTemplate = '''${applicationVersion}'''
                }
            }
        }
    }
}
```

**Pull request merged**
