### PR TITLE
Added file upload progress to the deploy script.

### PR DESCRIPTION
**Pull request by alxndrsn**
As per title.  Let me know if any questions.

### CODE REVIEW

**Comment by kenliu** [comment]
Looks great. Thanks for the PR. Am planning on doing a new release some time this week after some extensive testing and manual updates.

I had actually started working on this feature as well but what you came up with is great.

closed #11

**Comment by alxndrsn** [comment]
Sorry for the wasted effort.  Importing as there are 2 versions of the ProgressListener class - one deprecated - caused me a lot of bother when trying to get this working.

**Comment by kenliu** [comment]
no worries, your implementation is cleaner anyway ;) That's how it is with open source.

I'll add a note about the deprecated class.

**Comment by kenliu** [comment]
released this PR in 0.3-SNAPSHOT, would appreciate any help with testing before I release 0.3

**Comment by alxndrsn** [comment]
Hey, not sure if i'll get a chance to test this before next year.  We've noticed an intermittent bug though - when your internet connection is poor, the reported "uploaded size" can be more than the size of the file being uploaded.  It's quite frustrating (we have poor connection a lot of the time), but does not seem to cause problems with the uploaded data.

**Comment by kenliu** [comment]
I guess this is an issue with the underlying AWS SDK library. I reported it as a separate defect in case anyone else has the same problem.

**Pull request merged**
