### PR TITLE
Added jvm options to .ebextensions configuration.

### PR DESCRIPTION
**Pull request by alxndrsn**
As per the comment - really just a minor modification to my system properties config work.

### CODE REVIEW

**Comment by kenliu** [comment]
BTW I have started working on a comprehensive user manual here:

https://github.com/kenliu/grails-elastic-beanstalk/blob/master/src/asciidoc/manual.adoc

It would be good if you would update the documentation for this feature.

**Comment by alxndrsn** [comment]
Thanks, glad you like it.  Will put documentation on my todo list.

**Comment by kenliu** [comment]
created #18

**Comment by kenliu** [comment]
released this PR in 0.3-SNAPSHOT, would appreciate any help with testing before I release 0.3

see also [#19] that enables including files for .ebextensions in the war

**Pull request merged**
