### PR TITLE
AWS credentials configuration alternative

### PR DESCRIPTION
**Pull request by jvdrean**
Added a way to configure AWS credentials via grails-app/conf/Config.groovy and system properties

### CODE REVIEW

**Comment by kenliu** [comment]
Thanks for the pull request. I was trying to decide whether or not to allow loading AWS credentials from the Grails config because it seemed like a bad idea for people to put their AWS credentials inside the Grails config (because of source control).

Note that the plugin already supports reading the AWS credentials from System properties, but it is admittedly not well-documented. The properties are "AWSAccessKeyId" and "AWSSecretKey".

**Comment by jvdrean** [comment]
Hi, thanks for the merge! I saw the support for system properties (AWSAccessKeyId and AWSSecretKey) when I looked at the source. I still went ahead with the addition though, I'm used to put System.getProperty calls in Config.groovy (since it allows to externalise keys for plugins that don't support system props natively), and well, may be some other people will appreciate to handle all of them in a consistent manner :)

**Comment by kenliu** [comment]
You can find the detailed documentation in progress here:

https://github.com/kenliu/grails-elastic-beanstalk/blob/master/src/asciidoc/manual.adoc

**Comment by kenliu** [comment]
released this PR in 0.3-SNAPSHOT, would appreciate any help with testing before I release 0.3

**Comment by jvdrean** [comment]
I tested 0.3-SNAPSHOT and found a small bug, versionDescriptionTemplate and versionLabelTemplate have to be set in the config, otherwise you get:

```
groovy.lang.MissingMethodException: No signature of method: net.kenliu.awsebplugin.BeanstalkDeployer.generateVersionDescription() is applicable for argument types: (groovy.util.ConfigObject) values: [[:]]
Possible solutions: generateVersionDescription(java.lang.String), generateVersionDescription(java.lang.String, java.util.Date)
```

**Comment by kenliu** [comment]
good catch, thanks for your help. Will fix this and I plan to release 0.3 this weekend.

**Pull request merged**
